# ------------------------------------------------------------------
# Copyright (C) 2004 INRA <eugene@ossau.toulouse.inra.fr>
#
# This program is open source; you can redistribute it and/or modify
# it under the terms of the Artistic License (see LICENSE file).
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
#
# You should have received a copy of Artistic License along with
# this program; if not, please see http://www.opensource.org
#
# $Id$
# ------------------------------------------------------------------
# File:     Arabidopsis.exp
# Contents: Tests on Arabidopsis sesequences
# ------------------------------------------------------------------


foreach TEST $ArabidopsisTestList {

    # To follow execution
    puts "Performing $TEST Arabidopsis test"

    set test 0

    # Preparation of the parameter file with the correct sensors
    foreach sensor $SensorsList($TEST) \
	{set NewValueBase(Sensor.${sensor}.use) TRUE}
    ModifyParaValue ${EUGENE}.par  NewValueBase
    
    # Run EuGene
    catch {eval exec $EUGENE_DIR/$EUGENE $SEQ($TEST) > tmp%stdout}
    
    # Checking the output
    set test [diff $OUTPUT_DIR/$FILE_REF($TEST) tmp%stdout]
    if {$test == 1} {
	pass $TEST
    } else {
	fail $TEST
	catch {exec mv tmp%stdout $TRACE_DIR/$FILE_REF($TEST)}
    }
    
    # Remove temporary file
    catch {exec rm tmp%stdout}
    
    # Restore initial parameters values
    InitParameterFile ${EUGENE}.par $AllSensorsList $EUGENE_DIR

}