# ------------------------------------------------------------------
# Copyright (C) 2004 INRA <eugene@ossau.toulouse.inra.fr>
#
# This program is open source; you can redistribute it and/or modify
# it under the terms of the Artistic License (see LICENSE file).
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
#
# You should have received a copy of Artistic License along with
# this program; if not, please see http://www.opensource.org
#
# $Id$
# ------------------------------------------------------------------
# File:     Functional.exp
# Contents: Functional tests scripts
# ------------------------------------------------------------------


foreach TEST $FunctionalTestList {

    # To follow execution
    puts "Performing $TEST functional test"

    foreach seq $SEQ($TEST) {
	# Local variables 
	set test_std 0
	set test_png 0

	# Preparation of the parameter file with the correct sensors
	foreach sensor $SensorsList($TEST) \
	    {set NewValue${TEST}(Sensor.${sensor}.use) 1}
	ModifyParaValue $EUGENE_TEST_PAR  NewValue${TEST}

	# Open reference file
	set f [open $OUTPUT_DIR/$FILE_REF($TEST)_test {RDONLY}]
	set reference [read -nonewline $f]
	close $f

	# Get the sequence length
	set l [GetSeqLength $SEQ_DIR/$seq]

	# Run EuGene
	eval spawn $EUGENE_DIR/$EUGENE -A $EUGENE_DIR/$EUGENE_TEST_PAR $OPTIONS($TEST) -l $l $SEQ_DIR/$seq

	# Checking the output
	match_max 10000
	expect {
	    -re $reference {set test_std 1}
	    -re timeout {fail "$TEST (timeout)"}
	}

	# Checking the graphical output
	set test_png [diff $OUTPUT_DIR/$FILE_REF($TEST).png $IMG($TEST)]

	# No regression if the 2 tests are passed
	if {$test_std==1 && $test_png==1} {
	    pass "${TEST}"
	    exec rm $IMG($TEST)
	} else {
	    if {$test_std != 1} {
		fail "${TEST} (text)"
		eval exec $EUGENE_DIR/$EUGENE -A $EUGENE_DIR/$EUGENE_TEST_PAR \
		    $OPTIONS($TEST) -l $l \
		    $SEQ_DIR/$seq >& $TRACE_DIR/$FILE_REF($TEST)
		# Remove the first lines related to version number
		RemoveFirstLines $TRACE_DIR/$FILE_REF($TEST)
	    }
	    if {$test_png != 1} {
		fail "${TEST} (graph)"
		exec mv $IMG($TEST) $TRACE_DIR/$FILE_REF($TEST).png
	    }
	    catch {exec rm $IMG($TEST)}
	}

	# Restore initial parameters values
	InitParameterFile $EUGENE_TEST_PAR $AllSensorsList $EUGENE_DIR
    }
}