#============================================================================
#=             Copyright (c) 2002 by INRA. All rights reserved.             
#=                 Redistribution is not permitted without                  
#=                 the express written permission of INRA.                 
#=                     Mail : tschiex@toulouse.inra.fr                     
#=-------------------------------------------------------------------------
#= File         : EuGeneTk/Test/TestSuite/Optimization.exp
#= Description  : Parameters optimization test script
#= Authors      : P.Bardou, S.Foissac, M.J.Cros, A.Moisan, T.Schiex         
#===========================================================================


set test 0


# Run EuGene
catch {eval exec $EUGENE_DIR/$EUGENE -Z test > tmp%stdout}

# Checking the output
set test [diff $OUTPUT_DIR/$FILE_REF(Optimization) tmp%stdout]
if {$test == 1} {
    pass "Optimization"
} else {
    fail "Optimization"
    catch {exec mv tmp%stdout $TRACE_DIR/$FILE_REF(Optimization)}
}

# Remove temporary file
catch {exec rm tmp%stdout}



