# ------------------------------------------------------------------
# Copyright (C) 2004 INRA <eugene@ossau.toulouse.inra.fr>
#
# This program is open source; you can redistribute it and/or modify
# it under the terms of the Artistic License (see LICENSE file).
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
#
# You should have received a copy of Artistic License along with
# this program; if not, please see http://www.opensource.org
#
# $Id$
# ------------------------------------------------------------------
# File:     Units.exp
# Contents: Unit test script test each sensor separately
# ------------------------------------------------------------------


foreach TEST $AllSensorsList {

    # To follow execution
    puts "Performing $TEST unit test"

    # Run eugene
    if {$TEST != "Est" && $TEST != "Tester"} {
	eval exec $EUGENE_DIR/$EUGENE -A $EUGENE_DIR/$EUGENE_TEST_PAR \
	    $OPTIONS(Sensor) \
	    -D Sensor.${TEST}.use=1 $SEQ_DIR/$SEQ(Sensor) \
	2> tmp%stderr > tmp%stdout
    } else {
	if {$TEST == "Est"} {
	    eval exec $EUGENE_DIR/$EUGENE -A $EUGENE_DIR/$EUGENE_TEST_PAR \
		$OPTIONS(Sensor) \
		-D Sensor.${TEST}.use=1 -D Sensor.NG2.use=1 \
		$SEQ_DIR/$SEQ(Sensor) 2> tmp%stderr > tmp%stdout
	} else {
	    eval exec $EUGENE_DIR/$EUGENE -A $EUGENE_DIR/$EUGENE_TEST_PAR \
		$OPTIONS(Sensor) \
		-D Sensor.${TEST}.use=1 $SEQ_DIR/exSeqHom.fasta  \
		2> tmp%stderr > tmp%stdout
	}
    }

    set out [open tmp%stdout {RDONLY}]
    set err [open tmp%stderr {RDONLY}]
    set std [open tmp%$TEST w+]
    
    # Copy stderr and stdout in the reference file
    set f [read -nonewline $err]
    puts $std $f
    set f [read -nonewline $out]
    puts $std $f

    close $out
    close $err
    close $std

    exec rm tmp%stderr tmp%stdout

    # Remove the first lines related to version number
    RemoveFirstLines tmp%$TEST

    # Compare ingnoring the case of letters (Linux inf/SUN Inf)
    if {[file exists tmp%testdiff] == 1} {
	exec rm tmp%testdiff
    }
    catch {exec diff -i $OUTPUT_DIR/Output_${TEST} tmp%$TEST > tmp%testdiff }
    set t [open tmp%testdiff {RDONLY}]
    set difference [read $t]
    close $t
    if {$difference == ""} {
	pass "${TEST}"
	exec rm tmp%$TEST
    } else {
	fail "${TEST}"
	exec mv tmp%$TEST $TRACE_DIR/Output_${TEST}
    }

}

# Remove temporary files
catch {exec rm tmp%stdout}
catch {exec rm tmp%stderr}
catch {exec rm tmp%testdiff}
exec rm Sensor.EuStop.SpSn
